### ISSUE TITLE
Regression in v1.4

### ISSUE THREAD

**Issue by wokket** [erikbra/grate#232] opened 2022-09-06 02:19 UTC
Our CI on an existing grate project has started failing, the final green build was on V1.3.2, the first failed build was V1.4, and it has failed every run subsequent.

This migration is targeting a `localdb` sql instance.  Script to run the CI migration is:

``` pwsh
dotnet tool update grate -g

grate `
--files=../db `
--env=IntegrationTest `
--connstring="Server=(localdb)\MSSQLLocalDB;Integrated Security=true;Database=MyApp_IntegrationTest;Application Name=grate" `
--version=1.0 `
--silent `
--drop
```

Updating the deployment script to force install V1.3.2 lets the migration complete successfully again, ie replace the update command with:
``` pwsh
dotnet tool uninstall grate -g
dotnet tool install grate -g --version 1.3.2
```  
and it works fine again.

**To Reproduce**
Failure is a SQL Timeout while running a `runAfterCreateDatabase` script to enable RCSI, script content is:

``` sql
ALTER DATABASE {{DatabaseName}} SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE {{DatabaseName}} SET READ_COMMITTED_SNAPSHOT ON
```

** AzDo Output (slightly elided for confidentiality) **
```
Starting: Deploy Database for Integration Tests
    ==============================================================================
    Task         : PowerShell
    Description  : Run a PowerShell script on Linux, macOS, or Windows
    Version      : 2.200.0
    Author       : Microsoft Corporation
    Help         : []
    ==============================================================================
    Generating script.
    Formatted command: . 'D:\a\1\s\src\MyApp.Database\deployment\init_test_database.ps1'
    ========================== Starting Command Output ===========================
    "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\a9125961-11eb-4d77-811c-38ee4104f896.ps1'"
    You can invoke the tool using the following command: grate
    Tool 'grate' (version '1.4.0') was successfully installed.
    Initializing connections.
    Running grate v1.4.0.0 against (localdb)\MSSQLLocalDB - MyApp_IntegrationTest.
    Looking in ../db for scripts to run.
    ================================================================================
    Setup, Backup, Create/Restore/Drop
    ================================================================================
    grate has removed database (MyApp_IntegrationTest) if it existed.
    ================================================================================
    Grate Structure
    ================================================================================
    ================================================================================
    Versioning
    ================================================================================
     Migrating MyApp_IntegrationTest from version 0.0.0.0 to 1.0.
     Versioning MyApp_IntegrationTest database with version 1.0.
    ================================================================================
    Migration Scripts
    ================================================================================
    Skipping 'BeforeMigration', beforeMigration does not exist.
    Skipping 'AlterDatabase', alterDatabase does not exist.
                                                                                    
    Looking for Run After Create Database scripts in "../db\runAfterCreateDatabase".
    --------------------------------------------------------------------------------
      Running '001-RCSI.sql'.
    Error running script "001-RCSI.sql": Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
                                                                                    
    Looking for Permissions scripts in "../db\permissions". These scripts will run every time.
    --------------------------------------------------------------------------------
      Running 'RmtTVP.sql'.
    Error running script "RmtTVP.sql": Cannot find the type 'MediaTVP', because it does not exist or you do not have permission.
    Cannot find the object 'ProjectMedia', because it does not exist or you do not have permission.
    Cannot find the object 'ChildMedia', because it does not exist or you do not have permission.
    Skipping 'AfterMigration', afterMigration does not exist.
    Unhandled exception: grate.Exceptions.MigrationFailed: Migration failed due to errors:
     * Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
     * Cannot find the type 'MediaTVP', because it does not exist or you do not have permission.
    Cannot find the object 'ProjectMedia', because it does not exist or you do not have permission.
    Cannot find the object 'ChildMedia', because it does not exist or you do not have permission.
     ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
     ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
       at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
       at Microsoft.Data.SqlClient.TdsParserStateObject.CheckThrowSNIException()

```

Interestingly it continues on after the timeout, the timeout doesn't produce a stacktrace, but the following steps do?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22000.856

**Comment by wokket** [comment] 2022-09-06 03:15
Follow up: I can't repro this when running a locally compiled version of grate against the migration, either debug or release mode :(

100% reproducible when installed from `dotnet tool` or `winget`....  winget 1.4 is broken, 1.2 (the previous release) works fine.

**Comment by wokket** [comment] 2022-09-06 22:14
Finally got a repro in the tests, involving a `Drop` combined with an `Alter Database` in `RunAfterCreate`.

@erikbra I'm probably not going to get a chance to look at fixing this for a bit due to real™️work, but hopefully that repro is enough to help you nail it down.

**Comment by erikbra** [comment] 2022-10-01 17:32
Hi, @wokket - I'm very sorry that I haven't had the time to reply to this before now. There is a lot of real work(TM) on my part as well.

I don't know exactly what is happening here, but I know that there was a bit of wonkiness with opening and closing the connection multiple times in previous versions of grate. That _might_ have had the effect that your script worked.

I'm not familiar with these commands per se, but, looking at the example from MS, it looks like you _might_ be missing a `GO` statement after each of the commands? And, if the database connection was previously closed after running the `runAfterCreateDatabase`, that would effectively run the commands, the same way as a `GO` statement.

Could you please try if adding `GO` statements after each of the statements in your scripts solves the issue? 

Compare your script with the example here:

https://learn.microsoft.com/en-us/troubleshoot/sql/analysis-services/enable-snapshot-transaction-isolation-level#enable-the-snapshot-transaction-isolation-level

**Comment by wokket** [comment] 2022-10-02 06:20
Sorry mate, I've updated the script to match the MS sample, and it's still broken.  I'm afraid something has broken in that last release that stops me moving up to 1.4.

**Comment by erikbra** [comment] 2023-04-05 09:34
Hi again, @wokket - this one has been troubling me, but I haven't had time to look at it. 

But, I started looking at it now, and I cannot get this to work on 1.3.2 either. I've put your test that is failing on the 1.4.0 branch in a branch off 1.3.2, and it doesn't work there either. Are you sure this is a valid use case?

I ported this test: https://github.com/wokket/grate/commit/caafff06a1e761a565ed2ceb18b7e55c43e884e7
into this branch off 1.3.2: https://github.com/erikbra/grate/tree/chore/232-1.3.2-branch

I get the following error:
```
Microsoft.Data.SqlClient.SqlException : ALTER DATABASE statement not allowed within multi-statement transaction.
ALTER DATABASE statement not allowed within multi-statement transaction.
```

**Comment by wokket** [comment] 2023-04-05 10:51
Hey mate,

I have to confess when I did that test I focussed on reproducing the error, not checking the error _didn't_ occur in that test in the earlier codebase.

I've just committed a repro example that runs at the command line using the dotnet tool versions, just like my real projects.  If I grab that branch and run the `run-migration.ps1` script as-is (on 1.4) I get the error:
![image](https://user-images.githubusercontent.com/3802829/230059447-7ff8b6ba-1b4e-4ede-b9bc-ffb8bca784c8.png)



If I then change the powershell to install 1.3.2 instead of 1.4 and re-run, I get a green run:

![image](https://user-images.githubusercontent.com/3802829/230059659-f39ccac1-eeb3-4ebe-91df-407e5b9d257c.png)

**Comment by erikbra** [comment] 2023-04-05 14:57
One more thing - which version of SQL server are you running on? 2019? 2022? Docker, or any local install?

**Comment by erikbra** [comment] 2023-04-05 15:24
Hi again, @wokket  - I was able to reproduce the issue with running from the command-line. However, I'm running against SQL server in Docker, and if I turn off pooling in the connection string, everything works. I _think_ this might be it.

![image](https://user-images.githubusercontent.com/1628994/230126446-1b2d0931-23e2-4162-be8c-dfebfcdb5b6c.png)

**Comment by erikbra** [comment] 2023-04-05 15:27
There are quite a lot of changes in Microsoft.Data.SqlClient v 5.0, which we started using in grate 1.4 (https://github.com/dotnet/SqlClient/blob/main/release-notes/5.0/5.0.0.md). Could you please try to add `;Pooling=false` to your connection string, @wokket , and see if it works for you too? And, more importantly, does it solve your real-world scenario?

If this is the issue, we might consider just setting Pooling to false on the SqlConnection explicitly programatically, if nothing is explicitly specified in the connection string, as this is a rather hidden feature/bug, if we leave it up to the user

**Comment by wokket** [comment] 2023-04-05 19:23
Hey mate, nice catch.

I can confirm that adding `pooling=false` fixed the first of my real world projects, both the integration tests looking at localdb like the example above, and my dev Sql 2019 database running in docker.

I think you're onto something here...  Looks like there was a few transaction related bugs fixed between 5 and 5.0.2, hopefully this was one of them.

**Comment by erikbra** [comment] 2023-04-05 22:01
Well, lovely, then! I've created a PR that disables connection pooling explicitly for Sql Server, if nothing else is explicitly specified in the connection string: https://github.com/erikbra/grate/pull/322

**Comment by wokket** [comment] 2023-04-05 22:03
The issue was still there on SqlClient 5.0.2?

**Comment by erikbra** [comment] 2023-04-05 22:08
Yes, we're using 5.1.* now, so the issue is with pooling, most definitely. Because, when connection pooling is enabled, the connections are never properly closed, just returned to the connection pool, which makes sense if you're running a high-volume transactional app, but it doesn't make sense for grate, which does just one thing at a time, and gets confused if the connections are not closed when we expect them to be

**Comment by wokket** [comment] 2023-04-05 22:13
Yeah I'm not worried about negatives from disabling pooling with our use case, just wish we didn't have to have special case code ongoing.  When pooling even the connections aren't closed, they are 'reset' (`sp_connection_reset`??), which should have binned open transactions etc, so still feels like a bug somewhere to me, but least I can take a grate update now :)

Thanks for looking into it.

**Comment by erikbra** [comment] 2023-04-05 22:20
Yea, I agree, it doesn't feel "great" to me either, however, I've had do disable pooling in the connection strings of the unit tests a while ago due to concurrency issues as well. And, I think that even though it would be better to understand 100% what happened, and why, I'm leaning towards being pragmatic here, and saying that if it works, it works :)

If any of the hundreds of contributors to grate would like to deep dive more into this and create a PR, they're more than welcome ;)

**Closed** 2023-04-05 22:35 UTC
Labels: bug, triage
